**Prajwal R**

**AMB2175**

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
import pandas as pd

In [ ]:
df=pd.read_csv('agri_data (1).csv')
df

,Year,Region,Crop,Area_Hectares,Production_Tons,Rainfall_mm,Temperature_C
0,2018,North,Wheat,1200,3600,800,22
1,2018,South,Rice,1500,5000,1200,28
2,2019,North,Wheat,1250,3700,820,23
3,2019,South,Rice,1600,5200,1150,29
4,2020,North,Wheat,1300,3900,780,24
5,2020,South,Rice,1700,5400,1300,30
6,2021,North,Wheat,1280,4000,900,23
7,2021,South,Rice,1750,5600,1250,31
8,2022,North,Wheat,1350,4200,850,25
9,2022,South,Rice,1800,6000,1400,32

In [ ]:
pd.set_option('display.expand_frame_repr',False)
df

   Year Region   Crop  Area_Hectares  Production_Tons  Rainfall_mm  Temperature_C
0  2018  North  Wheat           1200             3600          800             22
1  2018  South   Rice           1500             5000         1200             28
2  2019  North  Wheat           1250             3700          820             23
3  2019  South   Rice           1600             5200         1150             29
4  2020  North  Wheat           1300             3900          780             24
5  2020  South   Rice           1700             5400         1300             30
6  2021  North  Wheat           1280             4000          900             23
7  2021  South   Rice           1750             5600         1250             31
8  2022  North  Wheat           1350             4200          850             25
9  2022  South   Rice           1800             6000         1400             32

In [ ]:
print('Tota rows:',len(df))
print('Total Columns:',len(df.columns))

Tota rows: 10
Total Columns: 7

In [ ]:
df.head(5)

   Year Region   Crop  Area_Hectares  Production_Tons  Rainfall_mm  Temperature_C
0  2018  North  Wheat           1200             3600          800             22
1  2018  South   Rice           1500             5000         1200             28
2  2019  North  Wheat           1250             3700          820             23
3  2019  South   Rice           1600             5200         1150             29
4  2020  North  Wheat           1300             3900          780             24

In [ ]:
df.tail(3)

   Year Region   Crop  Area_Hectares  Production_Tons  Rainfall_mm  Temperature_C
7  2021  South   Rice           1750             5600         1250             31
8  2022  North  Wheat           1350             4200          850             25
9  2022  South   Rice           1800             6000         1400             32

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Year             10 non-null     int64
 1   Region           10 non-null     object
 2   Crop             10 non-null     object
 3   Area_Hectares    10 non-null     int64
 4   Production_Tons  10 non-null     int64
 5   Rainfall_mm      10 non-null     int64
 6   Temperature_C    10 non-null     int64
dtypes: int64(5), object(2)
memory usage: 692.0+ bytes

In [ ]:
df.describe() #Statistical summary

              Year  Area_Hectares  Production_Tons  Rainfall_mm  Temperature_C
count    10.000000      10.000000        10.000000    10.000000      10.000000
mean   2020.000000    1473.000000      4660.000000  1045.000000      26.700000
std       1.490712     225.735834       875.848795   237.592087       3.713339
min    2018.000000    1200.000000      3600.000000   780.000000      22.000000
25%    2019.000000    1285.000000      3925.000000   827.500000      23.250000
50%    2020.000000    1425.000000      4600.000000  1025.000000      26.500000
75%    2021.000000    1675.000000      5350.000000  1237.500000      29.750000
max    2022.000000    1800.000000      6000.000000  1400.000000      32.000000

In [ ]:
df['Rainfall_mm']

0     800
1    1200
2     820
3    1150
4     780
5    1300
6     900
7    1250
8     850
9    1400
Name: Rainfall_mm, dtype: int64

In [ ]:
wheat=df[df['Crop']=='Wheat']
print(wheat)

   Year Region   Crop  Area_Hectares  Production_Tons  Rainfall_mm  Temperature_C
0  2018  North  Wheat           1200             3600          800             22
2  2019  North  Wheat           1250             3700          820             23
4  2020  North  Wheat           1300             3900          780             24
6  2021  North  Wheat           1280             4000          900             23
8  2022  North  Wheat           1350             4200          850             25

In [ ]:
yearly_production=df.groupby('Year')['Production_Tons'].sum()
print(yearly_production)

Year
2018     8600
2019     8900
2020     9300
2021     9600
2022    10200
Name: Production_Tons, dtype: int64

In [ ]:
import pandas as pd
index=['rice','wheat','maize','sugarcane']
production=pd.Series([30,4,50,60], index=index)
print(production)

In [ ]:
print(production.iloc[1])
print(production.loc['rice'])
print(production.max())
print(production.sum())

In [ ]:
#DataFrame = Hetergeneus inputs
import pandas as pd
df=pd.DataFrame({
    'name':['Akhil','Bobby','Charan'],
    'age' :[12,23,34],
    'City':['Delhi','Mumbai','chennai']
},index=[1,2,3])
print(df)
print('\n',df.loc[1])

In [ ]:
#Slicing
print(df)
print()
print(df.loc[[1,2],['name','age']])

In [ ]:
import pandas as pd
df = pd.DataFrame({
    'name': ['Akhil', 'Bobby', 'Charan'],
    'age': [12, 23, 34],
    'City': ['Delhi', 'Mumbai', 'chennai']
}, index=[1, 2, 3])

# loc uses label-based indexing (includes the stop index 3)
print("Using .loc[1:3]:")
print(df.loc[1:3])

# iloc uses integer-based indexing (excludes the stop index 3)
print("\nUsing .iloc[1:3]:")
print(df.iloc[0:2])

In [ ]:
print(df.loc[df['age']>28,['name','age']])

In [ ]:
print(df.iloc[[0,2]]) #Gives that particuar row

In [ ]:
print(df.iloc[[0,2],[1,2]]) #Rows and Columns

In [ ]:
print(df.iloc[:, 1])

In [ ]:
df['name']

In [ ]:
# A data frame is a 2D data structure.A tabe ie an excel sheet-made of mutipe series
data={
    'Farm':['Farm A','Farm B','Farm C','Farm D'],
    'Crop':['Wheat','Rice','Wheat','Maize'],
    'Area hectares':[10,15,8,12],
    'Production tons':[30,60,24,36]
}
df=pd.DataFrame(data,index=[1,2,3,4])
print(df)

In [ ]:
df.head(2) #Takes that particuar rows

In [ ]:
df.tail(2)

In [ ]:
df.info()

In [ ]:
df.describe() #Statistical summary , only gives integers

In [ ]:
#ADDING F NEW COLUMN
df['Yield t/ha']=df['Production tons']/df['Area hectares']
df['value']=[1,2,3,4]
print(df)

In [ ]:
df.iloc[[1,3],0:3]

In [ ]:
Wheat=(df['Crop']=='Wheat')
print(Wheat)

In [ ]:
Wheat=df[df['Crop']=='Wheat']
print(Wheat)

In [ ]:
high_Yield=df[df['Yield t/ha']>2]
print(high_Yield)

In [ ]:
sorted_df=df.sort_values(by='Production tons',ascending=False)
print(sorted_df)

In [ ]:
sorted_df=df.sort_values(by='Production tons',ascending=True)
print(sorted_df)

In [ ]:
avg_yield=df.groupby('Crop')['Yield t/ha'].mean()
print(avg_yield)

In [ ]:
avg_yield=df.groupby('Crop')['Yield t/ha'].sum()
print(avg_yield)

In [ ]:
#Pre processing data = to check the data whether it is right or wrong
import pandas as pd
import numpy as np

data = pd.DataFrame({
  'Plot':['A','B','C','D','E'],
  'Yield':[2500,np.nan,2800,np.nan,2600],
  'Rainfall':[150,200,np.nan,180,170],
  'Temperature':[28,30,29,np.nan,27]
})
print('==Data with Missing Values===')
print(data)
#Detecting missing data
print('\n==Detecting Missing Values===')
print('is null')
print(data.isnull())
print(f'\nTotal missing per column')
print(data.isnull().sum())

In [ ]:
print('\n==Filling strategies')
#Fill with mean
data_mean=data.copy()
print(data_mean)
# Updated to match the current column name 'Yield'
data_mean['Yield']=data_mean['Yield'].fillna(data_mean['Yield'].mean())
print('\n','Fill with mean')
print(data_mean['Yield'])

In [ ]:
data_median = data.copy()
data_median['Rainfall'] = data_median['Rainfall'].fillna(data_median['Rainfall'].median())
# Fixed: Changed 'rainfall' to 'Rainfall' to match the column name
print(data_median['Rainfall'])

In [ ]:
data_ffill=data.copy()
print(data_ffill)
data_fill=data_ffill.fillna(method='ffill')
print(data_fill)

In [ ]:
#Dropping Missing data
print('Dropping missing row')
data_dropped=data.dropna()
print(data_dropped)
print(f'original rows:{len(data)},After dropping:{len(data_dropped)}')

In [ ]:
import pandas as pd
df=pd.DataFrame({
    'A':[1,2,3],
    'B':[4,5,6]
})
print(df.loc[1,"A"])

2